// firebase_options.dart
//
// ⚠️ This file contains public Firebase configuration.
// According to Firebase documentation, these values are safe to be committed to version control.
// They only identify the project and do not grant access.
// Protection is done via Firebase Security Rules + App Check.
//
// GitHub secret scanning false positive for Google API keys in Firebase config.
//
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt4BceEsF5W3r1aUcvSjMZ8eA4vHVmnUM',
    appId: '1:394654138100:android:c8c635bd83e571275328a1',
    messagingSenderId: '394654138100',
    projectId: 'ishari-439af',
    storageBucket: 'ishari-439af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtpSQ1039cF991UZfZMgqhSL9s0crS70',
    appId: '1:394654138100:ios:4ce4f477758739385328a1',
    messagingSenderId: '394654138100',
    projectId: 'ishari-439af',
    storageBucket: 'ishari-439af.firebasestorage.app',
    iosBundleId: 'com.ishari.app',
  );
}
